name: miziptools
description: "Android App written in Flutter made to modify MiZip NFC tags."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.6.0-rc.4
  synchronized: ^3.3.0+3
  logging: ^1.3.0
  collection: ^1.19.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
